#! /bin/bash

function yn {
    local answer

    while true
    do
        echo -n $1
        read -p " y/n: " answer
        if [[ $answer == 'y' ]]
        then
            return 0
        elif [[ $answer == 'n' ]]
        then
            return 1
        fi
    done
}

read -p "---- Please enter the name of the scaffold you want to create: " scaffold

fields=""
while true
do
    read -p "---- Please enter the name of a field: " field
    read -p "---- Please enter the type of field $field: " type
    if [[ $fields == "" ]]
    then
        fields="$field:$type"
    else
        fields="$fields,$field:$type"
    fi
    if ! yn '---- Would you like to enter another field?'
    then
        break
    fi
done

echo "Running" php artisan make:scaffold --schema="$fields" $scaffold
php artisan make:scaffold --schema="$fields" $scaffold | tee tmp$$

echo "Patching app/Http/routes.php"
tail -1 tmp$$ >> app/Http/routes.php
rm tmp$$

echo "Migrating database"
php artisan migrate

model=`echo ${scaffold:0:1} | tr '[:lower:]' '[:upper:]'`${scaffold:1}
echo "Created a model in app/$model.php"
echo "Created a controller in app/Http/Controllers"
echo "Created views in resources/views"
echo "Created resource in app/Http/routes.php, see 'artisan route:list' for details."
