#! /bin/bash

function yn {
    local answer

    while true
    do
        echo -n $1
        read -p " y/n: " answer
        if [[ $answer == 'y' ]]
        then
            return 0
        elif [[ $answer == 'n' ]]
        then
            return 1
        fi
    done
}

if ! which laravel
then
    echo 'laravel not found'
    exit
fi

if ! which git
then
    echo 'git not found'
    exit
fi

read -p  "---- Please enter the name of the application you want to create: " application

# does the directory exist?
if [[ -d $application ]]
then
    if ! yn "---- Do you want to remove the existing application?"
    then
        exit
    fi

    echo "Attempting to reset all migrations"
    cd $application; php artisan migrate:reset; cd ..
    echo "Removing entire folder"
    rm -rf $application
fi

laravel new $application

cd $application
echo "Installing composer"
curl -sSk https://getcomposer.org/installer | php

echo "Installing l5scaffold"
php composer.phar require laralib/l5scaffold:dev-master

echo "Patching config/app"
sed -e "/'providers'/a\\
Laralib\\\L5scaffold\\\GeneratorsServiceProvider::class," < config/app.php > tmp$$
mv tmp$$ config/app.php

echo "Patching .env"
cat .env.example | sed -e '/DB_HOST/,/DB_PASSWORD/d' -e 's/mysql/sqlite/' > .env

echo "Creating empty database"
touch database/database.sqlite
