#! /bin/bash

function yn {
    local answer

    while true
    do
        echo -n $1
        read -p " y/n: " answer
        if [[ $answer == 'y' ]]
        then
            return 0
        elif [[ $answer == 'n' ]]
        then
            return 1
        fi
    done
}

read -p  "---- Please enter the name of the application you want to create: " application

# does the directory exist?
if [[ -d $application ]]
then
    if ! yn "---- Do you want to remove the existing application?"
    then
        exit
    fi

    echo "Attempting to reset all migrations"
    cd $application; php artisan migrate:reset
    echo "Removing entire folder"
    rm -rf $application
fi

~/.composer/vendor/bin/laravel new $application

(
    cd $application
    curl -sSk https://getcomposer.org/installer | php

    composer require laralib/l5scaffold:dev-master

    # awk "/'providers'/ { print; print \"Laralib\\\L5scaffold\\\GeneratorsServiceProvider::class,\" }" config/app.php > tmp$$
    sed -e "/'providers'/a\\
Laralib\\\L5scaffold\\\GeneratorsServiceProvider::class," < config/app.php > tmp$$
    mv tmp$$ config/app.php

    sed -e '/DB_HOST/,/DB_PASSWORD/d' -e 's/mysql/sqlite/' < .env > tmp$$
    mv tmp$$ .env

    touch database/database.sqlite
)
